FROM tensorflow/serving:latest

RUN apt update; \
    apt install -y python3; \
    apt install -y python3-pip; \
    pip3 install tensorflow==1.14 tornado requests numpy flask; \
    apt install -y vim; \
    apt install -y curl